# Generated by Django 2.2.4 on 2019-08-30 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 8, 30, 11, 33, 20, 562033, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrelloList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 8, 30, 11, 33, 20, 562355, tzinfo=utc))),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 8, 30, 11, 33, 20, 562667, tzinfo=utc))),
                ('labels', models.CharField(max_length=50)),
                ('trello_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.TrelloList')),
            ],
        ),
    ]
