# Generated by Django 2.2.4 on 2019-09-20 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0002_auto_20190920_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembers',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 20, 7, 31, 37, 379860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 20, 7, 31, 37, 380524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 20, 7, 31, 37, 380195, tzinfo=utc)),
        ),
    ]
